{
  tokens = [
    PLUS = "+"
    ARROW = "->"
    MINUS = "-"
    MUL = "*"
    DOT = "."
    NUMBER = "number"
    LET = "if"
    IF = "if"
    THEN = "then"
    ELSE = "else"
    EQUAL = "="
    IDENTIFIER = "id"

    space       = 'regexp:\s+'
  ]

  extends("sum_expr|constant|lookup_expr|simple")=simple
  extends("non_op_expr|expr")=expr

}
start ::= expr

expr ::=
    non_op_expr
    mul_expr

non_op_expr ::=
    assign_expr
  | simple

mul_expr ::=
    expr MUL expr

assign_expr ::=
    simple DOT IDENTIFIER EQUAL expr


simple ::=
    sum_expr
  //| lookup_expr
  | constant


sum_expr ::=
  simple PLUS simple

lookup_expr ::=
    simple DOT IDENTIFIER

constant ::=
    NUMBER