{
  tokens = [
    PLUS = "+"
    ARROW = "->"
    MINUS = "-"
    MUL = "*"
    DOT = "."
    NUMBER = "number"
    LET = "if"
    IF = "if"
    THEN = "then"
    ELSE = "else"
    EQUAL = "="
    IDENTIFIER = "id"
  ]

  extends(".*simple")=simple
  extends(".*expr")=expr

}

expr ::=
    block_expr
  | plus_operator_expr

block_expr ::=
    LET IDENTIFIER EQUAL expr
  | IF expr THEN expr (ELSE expr)?

plus_operator_expr ::=
  expr '+' expr

simple_expr ::=
  simple

simple ::=
    constant_simple
  | dot_operator_simple

value ::=
    IDENTIFIER
  | constant

constant ::=
    NUMBER

constant_simple ::=
    NUMBER



dot_operator_simple ::=
  simple '.' simple

